name: Playwright Tests
run-name: Playwright Tests - ${{ inputs.test_case }} on ${{ inputs.baseUrl }} (by @${{ github.actor }})
on:
  workflow_dispatch:
    inputs:
      test_case:
        description: 'Test case to run'
        required: true
        default: 'WF_CALADN_03.spec.js'
        type: choice
        options:
          - 'ALL'
          - 'WF_CALADN_01.spec.js'
          - 'WF_CALADN_02.spec.js'
          - 'WF_CALADN_03.spec.js'
          - 'WF_CALADN_04.spec.js'
          - 'WF_CALADN_05.spec.js'
          - 'WF_CALADN_31.spec.js'
          - 'WF_CALADN_32.spec.js'
          - 'WF_CALADN_32A.spec.js'
          - 'WF_CALADN_33.spec.js'
          - 'WF_CALADN_33A.spec.js'
          - 'WF_CALADN_39.spec.js'
          - 'WF_CALADN_40.spec.js'
          - 'WF_CALADN_41.spec.js'
          - 'WF_CALADN_42.spec.js'
          - 'WF_CALADN_45.spec.js'
          - 'WF_CALADN_46.spec.js'
          - 'WF_CALADN_47.spec.js'
          - 'WF_CALADN_48.spec.js'
          - 'WF_CALADN_125.spec.js'
          - 'WF_CALADN_126.spec.js'
      baseUrl:
        description: 'Select Target Base URL'
        required: true
        type: choice
        default: 'http://release-uat.healync.com.s3-website.ap-south-1.amazonaws.com'
        options:
          - 'http://frontend-uat.healync.com'
          - 'http://release-uat.healync.com.s3-website.ap-south-1.amazonaws.com'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ inputs.test_case }}" == "ALL" ]; then
            echo 'matrix=["WF_CALADN_01.spec.js","WF_CALADN_02.spec.js","WF_CALADN_03.spec.js","WF_CALADN_04.spec.js","WF_CALADN_05.spec.js","WF_CALADN_31.spec.js","WF_CALADN_32.spec.js","WF_CALADN_32A.spec.js","WF_CALADN_33.spec.js","WF_CALADN_33A.spec.js","WF_CALADN_39.spec.js","WF_CALADN_40.spec.js","WF_CALADN_41.spec.js","WF_CALADN_42.spec.js","WF_CALADN_45.spec.js","WF_CALADN_46.spec.js","WF_CALADN_47.spec.js","WF_CALADN_48.spec.js","WF_CALADN_125.spec.js","WF_CALADN_126.spec.js"]' >> "$GITHUB_OUTPUT"
          else
            echo "matrix=[\"${{ inputs.test_case }}\"]" >> "$GITHUB_OUTPUT"
          fi

  test:
    needs: setup
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        test_case: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Test Case
      env:
        BASE_URL: ${{ inputs.baseUrl }}
      run: npx playwright test tests/${{ matrix.test_case }}
    - name: Upload HTML Report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ strategy.job-index }}-${{ matrix.test_case }}
        path: playwright-report/
        retention-days: 30